var Wami=window.Wami||{};Wami._callbacks=Wami._callbacks||{};
Wami.setup=function(callback,id,swfurl){function supportsTransparency(){return navigator.platform.indexOf("Linux")==-1}function embedWamiSWF(id,initfn){var flashVars={visible:false,loadedCallback:initfn,allrates:true,stream:true,rate:16E3};var params={allowScriptAccess:"always"};if(supportsTransparency())params.wmode="transparent";if(typeof console!=="undefined")flashVars.console=true;var version="10.0.0";document.getElementById(id).innerHTML="WAMI requires Flash "+version+" or greater<br />https://get.adobe.com/flashplayer/";
Wami.swfobject.embedSWF(swfurl,id,214,137,version,null,flashVars,params);Wami.swfobject.createCSS("#"+id,"outline:none")}function checkRemembered(finishedfn){var id="Wami-SWF"+Math.random();var div=document.createElement("div");div.style.top="-999px";div.style.left="-999px";div.setAttribute("id",id);var body=document.getElementsByTagName("body").item(0);body.appendChild(div);Wami._callbacks[id]=function(){var swf=document.getElementById(id);Wami._remembered=swf.getSettings().microphone.granted;var div=
document.getElementById(id);Wami.swfobject.removeSWF(id);eval(finishedfn+"()")};embedWamiSWF(id,"Wami._callbacks['"+id+"']")}function delegateWamiAPI(){function delegate(name){Wami[name]=function(){return recorder[name].apply(recorder,arguments)}}var recorder=document.getElementById(id);delegate("startPlaying");delegate("stopPlaying");delegate("startRecording");delegate("stopRecording");delegate("startListening");delegate("stopListening");delegate("getRecordingLevel");delegate("getPlayingLevel");
delegate("setSettings");Wami.getSettings=function(){var settings=recorder.getSettings();settings.microphone.remembered=Wami._remembered;return settings};Wami.showSecurity=function(panel,startfn,finishedfn,failfn){Wami._callbacks["securitypanelclosed"]=function(){checkRemembered(finishedfn)};recorder.showSecurity(panel,startfn,"Wami._callbacks['securitypanelclosed']",failfn)};Wami.show=function(){if(!supportsTransparency())recorder.style.visibility="visible"};Wami.hide=function(){if(!supportsTransparency())recorder.style.visibility=
"hidden"};Wami._remembered=recorder.getSettings().microphone.granted;callback()}Wami.swfobject=Wami.swfobject||swfobject;if(Wami.startRecording){callback();return}if(typeof id=="undefined")alert("Need an element ID to place the Flash object.");if(typeof swfurl=="undefined")swfurl="Wami.swf";Wami._callbacks["initswf"]=delegateWamiAPI;embedWamiSWF(id,"Wami._callbacks['initswf']")};Wami.utils=Wami.utils||{};
Wami.utils.stringifyJSONJSON=function(obj){if(!JSON.stringify)alert("This browser does not support JSON.stringify");return JSON.stringify(obj)};Wami.utils.parseJSON=function(str){if(!Wami.utils.parseJSON)alert("This browser does not support Wami.utils.parseJSON");return Wami.utils.parseJSON(obj)};Wami.utils.removeChildren=function(div){if(div&&div.hasChildNodes())for(;div.childNodes.length>=1;)div.removeChild(div.firstChild)};
Wami.utils.debug=function(message){if(typeof console=="undefined");else if(Wami.utils.gup("debug")=="alert")alert(message);else console.log(message)};Wami.utils.specialEncode=function(input){return Wami.utils.encode64(input).replace("/","==S")};
Wami.utils.encode64=function(input){var keyStr="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/=";input=escape(input);var output="";var chr1;var chr2;var chr3="";var enc1;var enc2;var enc3;var enc4="";var i=0;do{chr1=input.charCodeAt(i++);chr2=input.charCodeAt(i++);chr3=input.charCodeAt(i++);enc1=chr1>>2;enc2=(chr1&3)<<4|chr2>>4;enc3=(chr2&15)<<2|chr3>>6;enc4=chr3&63;if(isNaN(chr2))enc3=enc4=64;else if(isNaN(chr3))enc4=64;output=output+keyStr.charAt(enc1)+keyStr.charAt(enc2)+keyStr.charAt(enc3)+
keyStr.charAt(enc4);chr1=chr2=chr3="";enc1=enc2=enc3=enc4=""}while(i<input.length);return output};Wami.utils.gup=function(name){var regexS="[\\?&]"+name+"=([^&#]*)";var regex=new RegExp(regexS);var tmpURL=window.location.href;var results=regex.exec(tmpURL);if(results==null)return null;else return results[1]};
Wami.utils.setCookie=function(cookieName,cookieValue,nDays){var today=new Date;var expire=new Date;if(nDays==null||nDays==0)nDays=1;expire.setTime(today.getTime()+36E5*24*nDays);document.cookie=cookieName+"="+escape(cookieValue)+";expires="+expire.toGMTString()};
Wami.utils.getCookie=function(name){var start=document.cookie.indexOf(name+"=");var len=start+name.length+1;if(!start&&name!=document.cookie.substring(0,name.length))return null;if(start==-1)return null;var end=document.cookie.indexOf(";",len);if(end==-1)end=document.cookie.length;return unescape(document.cookie.substring(len,end))};Wami.utils.xml=function(){};
Wami.utils.xml.fromString=function(xmlString){if(typeof DOMParser!="undefined"){var doc=(new DOMParser).parseFromString(xmlString,"application/xml");return doc}else if(typeof ActiveXObject!="undefined"){doc=Wami.utils.xml.newDocument();doc.loadXML(xmlString);return doc}else{var url="data:text/xml;charset=utf-8,"+encodeURIComponent(xmlString);var request=new XMLHttpRequest;request.open("GET",url,false);request.send(null);return request.responseXML}};
Wami.utils.xml.toString=function(xmlNode){var serialized;try{serializer=new XMLSerializer;serialized=serializer.serializeToString(xmlNode)}catch(e){serialized=xmlNode.xml}return serialized};Wami.utils.xml.newRequest=function(){var xmlhttp=false;if(!xmlhttp&&typeof XMLHttpRequest!="undefined")try{xmlhttp=new XMLHttpRequest}catch(e){xmlhttp=false}if(!xmlhttp&&window.createRequest)try{xmlhttp=window.createRequest()}catch(e$$0){xmlhttp=false}return xmlhttp};
Wami.utils.xml.newDocument=function(rootTagName,namespaceURL){if(!rootTagName)rootTagName="";if(!namespaceURL)namespaceURL="";if(document.implementation&&document.implementation.createDocument)return document.implementation.createDocument(namespaceURL,rootTagName,null);else{var doc=new ActiveXObject("MSXML2.DOMDocument");if(rootTagName){var prefix="";var tagname=rootTagName;var p=rootTagName.indexOf(":");if(p!=-1){prefix=rootTagName.substring(0,p);tagname=rootTagName.substring(p+1)}if(namespaceURL){if(!prefix)prefix=
"a0"}else prefix="";var text="<"+(prefix?prefix+":":"")+tagname+(namespaceURL?" xmlns:"+prefix+'="'+namespaceURL+'"':"")+"/>";doc.loadXML(text)}return doc}};
(function(){function parse(s){var buf=new BufferClass(16);var i=0;var ton=toNumber;s.toUpperCase().replace(/[0-9A-F][0-9A-F]/g,function(octet){buf[i++]=toNumber[octet]});return buf}function unparse(buf){var tos=toString;var b=buf;return tos[b[0]]+tos[b[1]]+tos[b[2]]+tos[b[3]]+"-"+tos[b[4]]+tos[b[5]]+"-"+tos[b[6]]+tos[b[7]]+"-"+tos[b[8]]+tos[b[9]]+"-"+tos[b[10]]+tos[b[11]]+tos[b[12]]+tos[b[13]]+tos[b[14]]+tos[b[15]]}function uuid(fmt,buf,offset){var b32=4294967296;var ff=255;var b=fmt!="binary"?_buf:
buf?buf:new BufferClass(16);var i=buf&&offset||0;r=Math.random()*b32;b[i++]=r&ff;b[i++]=(r=r>>>8)&ff;b[i++]=(r=r>>>8)&ff;b[i++]=(r=r>>>8)&ff;r=Math.random()*b32;b[i++]=r&ff;b[i++]=(r=r>>>8)&ff;b[i++]=(r=r>>>8)&15|64;b[i++]=(r=r>>>8)&ff;r=Math.random()*b32;b[i++]=r&63|128;b[i++]=(r=r>>>8)&ff;b[i++]=(r=r>>>8)&ff;b[i++]=(r=r>>>8)&ff;r=Math.random()*b32;b[i++]=r&ff;b[i++]=(r=r>>>8)&ff;b[i++]=(r=r>>>8)&ff;b[i++]=(r=r>>>8)&ff;return fmt===undefined?unparse(b):b}var BufferClass=typeof Buffer=="function"?
Buffer:Array;var _buf=new BufferClass(16);var toString=[];var toNumber={};for(var i$$0=0;i$$0<256;i$$0++){toString[i$$0]=(i$$0+256).toString(16).substr(1).toUpperCase();toNumber[toString[i$$0]]=i$$0}uuid.parse=parse;uuid.unparse=unparse;uuid.BufferClass=BufferClass;Wami.utils.uuid=uuid})();
Wami.utils._Deferred=function(){var names="Boolean Number String Function Array Date RegExp Object".split(" ");var class2type={};for(var i$$0=0;i$$0<names.length;i$$0++){var name=names[i$$0];class2type["[object "+name+"]"]=name.toLowerCase()}var callbacks=[];var fired;var firing;var cancelled;var deferred={finished:function(){if(!cancelled){var args=arguments;var i;var length;var elem;var type;var _fired;if(fired){_fired=fired;fired=0}for(i=0,length=args.length;i<length;i++){elem=args[i];type=elem==
null?String(elem):class2type[Object.prototype.toString.call(elem)]||"object";if(type==="array")deferred.finished.apply(deferred,elem);else if(type==="function")callbacks.push(elem)}if(_fired)deferred.resolveWith(_fired[0],_fired[1])}return this},resolveWith:function(context,args){if(!cancelled&&!fired&&!firing){args=args||[];firing=1;try{for(;callbacks[0];)callbacks.shift().apply(context,args)}finally{fired=[context,args];firing=0}}return this},resolve:function(){deferred.resolveWith(this,arguments);
return this},isResolved:function(){return!!(firing||fired)},cancel:function(){cancelled=1;callbacks=[];return this}};return deferred};
Wami.utils.createDeferred=function(){var deferred=Wami.utils._Deferred();var failDeferred=Wami.utils._Deferred();var startDeferred=Wami.utils._Deferred();deferred.started=startDeferred.finished;deferred.resolveStart=startDeferred.resolve;deferred.failed=failDeferred.finished;deferred.rejectWith=failDeferred.resolveWith;deferred.reject=failDeferred.resolve;deferred.isRejected=failDeferred.isResolved;deferred.finished(failDeferred.cancel).failed(deferred.cancel);delete deferred.cancel;return deferred};
Wami.state={};Wami.state.IDLE="idle";Wami.state.RECORD="record";Wami.state.PLAY="play";Wami.event={};Wami.event.ERROR="error";Wami.event.STARTING="starting";Wami.event.STARTED="started";Wami.event.ALIVE="alive";Wami.event.STOPPING="stopping";Wami.event.STOPPED="stopped";
Wami.App=function(options){if(!options)return false;if(!this.validateOptions(options))return;if(_gWamiAppSingleton){alert("Error: You should only create one Wami.App per page");return}_gWamiAppSingleton=this;this._actions=new Array;this._listeners=new Array;this.setupMeters();this._wamiResponseFormat="json";this._wamiResponseHandlers={onReady:options.onReady,onSecurity:options.onSecurity,onRecognitionResult:options.onRecognitionResult,onRecognition:options.onRecognition,onResult:options.onResult,
onError:options.onError,onTimeout:options.onTimeout,onMessage:options.onMessage};if(options.onEvent)this.listen(options.onEvent);var that=this;var fnname=Wami.utils.wrapTempFn(function(data){that._params=data;that.setupDivs(options);var gui=that.setupGUI(options.guiID);that.setupSecurity(gui);that.initialize(options)});var url=Wami.utils.getServletUrl("content")+"?path=params.js&prettyPrint=true&callback="+fnname;if(options.devKey)url+="&devKey="+options.devKey;this.appendScript(url);if(options.environment){this._wamiEnvironment=
options.environment;this.setupEnvironment(options.environment)}else this._wamiEnvironment=null;return true};Wami.settings={};Wami.settings.PRIVACY="privacy";Wami.settings.MICROPHONE="microphone";
Wami.App.prototype.validateOptions=function(options){if(options.secID)alert("options.secID is deprecated in favor of options.appID.");if(options.configOptions){alert("options.configOptions is deprecated.  Please follow the documentation at: http://wami.csail.mit.edu/documentation.html");return false}if(options.audioOptions){alert("options.audioOptions is deprecated.  Please follow the documentation at: http://wami.csail.mit.edu/documentation.html");return false}return true};
Wami.App.prototype.setupDivs=function(options){function appendSubdiv(id){var subid=Wami.utils.uuid();var guidiv=document.getElementById(id);var subdiv=document.createElement("div");subdiv.setAttribute("id",subid);guidiv.appendChild(subdiv);return subid}if(!options.appID&&!options.guiID){options.appID=Wami.utils.uuid();options.guiID=options.appID;var div=document.createElement("div");div.setAttribute("id",options.guiID);document.body.insertBefore(div,document.body.firstChild)}else if(options.appID)options.guiID=
options.appID;else if(options.guiID)options.appID=options.guiID;options.guiID=appendSubdiv(options.guiID);options.appID=appendSubdiv(options.appID)};
Wami.App.prototype.setupSecurity=function(gui){var that=this;if(!this._wamiResponseHandlers.onSecurity)this._wamiResponseHandlers.onSecurity=function(){var settings=that.getSettings();Wami.utils.debug("Security Granted - "+settings.microphone.granted);Wami.utils.debug("Security Remembered - "+settings.microphone.remembered);settings=that.getSettings();if(!settings.microphone.granted){var security=that.settings(Wami.settings.PRIVACY);if(gui)gui.hideButton();security.show().failed(function(msg){alert(msg)})}else if(gui)gui.showButton()}};
Wami.App.prototype.getSettings=function(){var settings=Wami.getSettings();if(!settings.microphone)settings.microphone={granted:true,remembered:true};return settings};
Wami.App.prototype.settings=function(type){var that=this;if(!this._settings)this._settings=new Array;if(!this._settings[type])this._settings[type]={onClose:function(callback){this._onClose=callback},show:function(){var deferred=Wami.utils.createDeferred();deferred.resolveStart();var panel=this;var startfn=Wami.utils.wrapTempFn(function(){Wami.show()});var finishfn=Wami.utils.wrapTempFn(function(){Wami.hide();if(panel._onClose)panel._onClose();deferred.resolveWith(panel,[that.getSettings()])});var failfn=
Wami.utils.wrapTempFn(function(msg){Wami.hide();deferred.rejectWith(panel,[msg])});if(Wami.showSecurity)Wami.showSecurity(type,startfn,finishfn,failfn);else{var msg$$0="No Wami.showSecurity settings available for this browser.";deferred.rejectWith(panel,[msg$$0])}return deferred}};return this._settings[type]};
Wami.App.prototype.setupGUI=function(guiID){function background(index){if(index==1)return"-56px 0px";if(index==2)return"0px 0px";if(index==3)return"-112px 0";alert("Background not found: "+index)}function meter(index,offset){var top=5;if(offset)top+=offset;if(index==1)return"-169px "+top+"px";if(index==2)return"-189px "+top+"px";if(index==3)return"-249px "+top+"px";if(index==4)return"-209px "+top+"px";alert("Meter not found: "+self.type+" "+index)}if(!guiID)return null;var that=this;var div=document.createElement("div");
div.style.position="relative";var guidiv=document.createElement("div");guidiv.style.width="56px";guidiv.style.height="63px";guidiv.style.cursor="pointer";guidiv.style.background="url("+this.urls().buttons()+") no-repeat";guidiv.style.backgroundPosition=background(1);div.appendChild(guidiv);var micColorDiv=document.createElement("div");micColorDiv.style.width="20px";micColorDiv.style.height="63px";micColorDiv.style.margin="auto";micColorDiv.style.cursor="pointer";micColorDiv.style.background="url("+
this.urls().buttons()+") no-repeat";micColorDiv.style.backgroundPosition=meter(2);guidiv.appendChild(micColorDiv);var micBlackDiv=document.createElement("div");micBlackDiv.style.width="20px";micBlackDiv.style.height="63px";micBlackDiv.style.margin="auto";micBlackDiv.style.cursor="pointer";micBlackDiv.style.background="url("+this.urls().buttons()+") no-repeat";micBlackDiv.style.backgroundPosition=meter(1);micColorDiv.appendChild(micBlackDiv);var waitDiv=document.createElement("div");waitDiv.style.width=
"35px";waitDiv.style.height="35px";waitDiv.style.margin="auto";waitDiv.style.paddingTop="23px";waitDiv.style.paddingLeft="10px";waitDiv.style.display="none";waitDiv.style.background="url("+this.urls().loading()+") center center no-repeat";waitDiv.setAttribute("margin","0 auto");guidiv.appendChild(waitDiv);var mouseOverMic=function(){guidiv.style.backgroundPosition=background(3)};var mouseOutMic=function(){guidiv.style.backgroundPosition=background(1)};var menuShowing=false;var gui={clicked:function(e){var rightclick=
false;if(!e)e=window.event;if(e.which)rightclick=e.which==3;else if(e.button)rightclick=e.button==2;if(!rightclick&&!menuShowing)if(that.getState()==Wami.state.IDLE)that.record();else that.stop();return false},showReady:function(){waitDiv.style.display="none";micBlackDiv.style.display="block";micColorDiv.style.display="block";micBlackDiv.style.backgroundPosition=meter(1);micColorDiv.style.backgroundPosition=meter(1);guidiv.style.backgroundPosition=background(1);guidiv.onmouseover=mouseOverMic;guidiv.onmouseout=
mouseOutMic;var g=this;guidiv.onclick=function(e){g.clicked(e)};guidiv.style.zIndex=1E3},hideButton:function(){guidiv.style.display="none"},showButton:function(){guidiv.style.display="block"},showDisabled:function(){waitDiv.style.display="none";micBlackDiv.style.display="block";micColorDiv.style.display="block";micBlackDiv.style.backgroundPosition=meter(3,5);micColorDiv.style.backgroundPosition=meter(3,5);guidiv.style.backgroundPosition=background(2);guidiv.onmouseover=null;guidiv.onmouseout=null;
guidiv.onclick=null},showWaiting:function(){waitDiv.style.display="block";micBlackDiv.style.display="none";micColorDiv.style.display="none";guidiv.style.backgroundPosition="0 0";guidiv.onmouseover=null;guidiv.onmouseout=null},showRecordMeter:function(playing){waitDiv.style.display="none";micBlackDiv.style.backgroundPosition=meter(1,5);micColorDiv.style.backgroundPosition=meter(2,5);micBlackDiv.style.display="block";micColorDiv.style.display="block";guidiv.onmouseout=null;guidiv.onmouseover=null},
showPlayMeter:function(){waitDiv.style.display="none";micBlackDiv.style.backgroundPosition=meter(1,5);micColorDiv.style.backgroundPosition=meter(4,5);micBlackDiv.style.display="block";micColorDiv.style.display="block";guidiv.onmouseout=null;guidiv.onmouseover=null}};this.handle(function(state,event,data){Wami.utils.debug("State("+state+") "+"Event("+event+") Data("+data+")");if(event==Wami.event.STOPPED){if(state==Wami.state.RECORD||state==Wami.state.PLAY)gui.showReady();if(state==Wami.state.IDLE)gui.showDisabled()}else if(event==
Wami.event.STARTING){gui.showButton();gui.showWaiting()}else if(event==Wami.event.STARTED)if(state==Wami.state.PLAY)gui.showPlayMeter();else if(state==Wami.state.RECORD)gui.showRecordMeter();else{if(state==Wami.state.IDLE){gui.showButton();gui.showReady()}}else if(event==Wami.event.ALIVE){if(state==Wami.state.PLAY||state==Wami.state.RECORD){var level=data;var totalHeight=31;var maxHeight=9;var height=maxHeight+totalHeight-Math.floor(level/100*totalHeight);micBlackDiv.style.height=height+"px"}}else if(event==
Wami.event.ERROR)gui.showDisabled()});var menuDiv=document.createElement("div");menuDiv.style.display="none";menuDiv.style.fontFamily="Verdana, Arial, Helvetica, sans-serif";menuDiv.style.fontSize="11px";menuDiv.style.width="75px";menuDiv.style.position="absolute";menuDiv.style.border="solid 1px #CCCCCC";menuDiv.style.background="#EEEEEE";var createMenuItem=function(text,callback){var menuItem=document.createElement("div");menuItem.appendChild(document.createTextNode(text));menuItem.onclick=callback;
menuItem.style.padding="1px 5px 1px 5px";menuItem.onmouseover=function(){menuItem.style.background="#3399FF";menuItem.style.color="#FFFFFF"};menuItem.onmouseout=function(){menuItem.style.background="#EEEEEE";menuItem.style.color="#000000"};menuDiv.appendChild(menuItem)};that=this;createMenuItem("Settings...",function(){gui.hideButton();var settings=that.settings(Wami.settings.MICROPHONE);menuDiv.style.display="none";settings.show().failed(function(msg){alert(msg)}).finished(function(){gui.showButton()})});
createMenuItem("Close",function(){menuDiv.style.display="none";menuShowing=false});guidiv.appendChild(menuDiv);guidiv.oncontextmenu=function(e){var style=menuDiv.style;if(style.pixelLeft){style.pixelLeft=event.clientX+document.body.scrollLeft;style.pixelTop=event.clientY+document.body.scrollTop}else{style.left=e.clientX+document.body.scrollLeft;style.top=e.clientY+document.body.scrollTop}style.display="";menuShowing=true;return false};var elem=document.getElementById(guiID);if(elem)elem.appendChild(div);
else alert("Could not find element on page named "+guiID);return gui};Wami.App.prototype.setMeterInterval=function(interval){this._meterInterval=interval};Wami.App.prototype.handle=function(callback){var that=this;callback(this.getState(),this.getLastEvent());that._listeners.push(callback);return{destroy:function(){that._listeners.splice(that._listeners.indexOf(callback),1);delete callback}}};
Wami.App.prototype.fireAudioEvent=function(state,event,data){this._state=state;this.fireEvent(this._listeners,state,event,data);this._lastEvent=event};Wami.App.prototype.fireEvent=function(listeners,state,event,data){for(var i=0;i<listeners.length;i++)listeners[i](state,event,data)};
Wami.App.prototype.setupMeters=function(){var that=this;this._state=Wami.state.IDLE;this._lastEvent=Wami.event.STARTING;this.handle(function(state,event,data){if(state==Wami.state.RECORD&&event==Wami.event.STARTED)that.startMeter(Wami.state.RECORD);else if(state==Wami.state.PLAY&&event==Wami.event.STARTED)that.startMeter(Wami.state.PLAY);else if(event==Wami.event.STOPPED)that.stopMeter()})};
Wami.App.prototype.startMeter=function(state){var that=this;var interval=this._meterInterval;if(!interval)interval=100;this._levelMeter=setInterval(function(){var level=that.getAudioLevel();if(that.getState()==Wami.state.RECORD||that.getState()==Wami.state.PLAY)that.fireAudioEvent(state,Wami.event.ALIVE,level)},interval)};Wami.App.prototype.stopMeter=function(){if(this._levelMeter)clearInterval(this._levelMeter)};
Wami.App.prototype.initialize=function(options){function init(){if(!that._isReady){that._isReady=true;that.wamiPoll();that.fireAudioEvent(Wami.state.IDLE,Wami.event.STARTED);that.fireAudioEvent(Wami.state.IDLE,Wami.event.ALIVE);that.handleCallback("onReady",that._wsessionid)}}if(options.grammar){this.configure(options,options.grammar);if(options.sessionPlayback)this._playbackID=options.sessionPlayback;if(this._playbackID)this.startPlayback(this._playbackID)}this._wsessionid=this.isPlayingBack()?this._playbackID:
this._params.wsessionid;var that=this;Wami.setup(function(){if(Wami.showSecurity&&!that.getSettings().microphone.granted){that.settings(Wami.settings.PRIVACY).onClose(init);that.handleCallback("onSecurity")}else init()},options.appID,that.urls().swf())};
Wami.App.prototype.configure=function(options,grammar,callback){var xmlDoc=Wami.utils.xml.newDocument("update");var root=xmlDoc.firstChild;root.setAttribute("type","configure");root.setAttribute("wsessionid",this._params.wsessionid);if(grammar&&grammar.aggregate)options.sendAggregates=grammar.aggregate;if(grammar&&grammar.incremental)options.sendIncrementalResults=grammar.incremental;if(grammar&&grammar.split)options.splitTag=grammar.split;if(!options.sendIncrementalResults)options.sendIncrementalResults=
false;if(!options.sendAggregates)options.sendAggregates=false;if(typeof options!="undefined"){this.appendParam(xmlDoc,root,"sendIncrementalResults",options.sendIncrementalResults);this.appendParam(xmlDoc,root,"sendAggregates",options.sendAggregates);this.appendParam(xmlDoc,root,"splitTag",options.splitTag);this.appendParam(xmlDoc,root,"locationProtocol",location.protocol);this.appendParam(xmlDoc,root,"locationDomain",document.domain);this.appendParam(xmlDoc,root,"locationPort",location.port);this.appendParam(xmlDoc,
root,"locationPath",location.pathname);if(options.recordOnly)this.appendParam(xmlDoc,root,"recordOnly",options.recordOnly);if(options.devKey)this.appendParam(xmlDoc,root,"jsapiDevKey",options.devKey)}if(typeof grammar!="undefined")this.appendGrammar(xmlDoc,root,grammar);this.postXML(xmlDoc,callback)};
Wami.App.prototype.setGrammar=function(grammar){var xmlDoc=Wami.utils.xml.newDocument("update");var root=xmlDoc.firstChild;root.setAttribute("type","configure");this.appendGrammar(xmlDoc,root,grammar);this.postXML(xmlDoc)};
Wami.App.prototype.speak=function(text,options){var xmlDoc=Wami.utils.xml.newDocument("update");var root=xmlDoc.firstChild;root.setAttribute("type","speak");var params=xmlDoc.createElement("params");for(var name in options){var param=xmlDoc.createElement("param");param.setAttribute("name",name);param.setAttribute("value",options[name]);params.appendChild(param)}var elem=xmlDoc.createElement("synth_string");elem.appendChild(xmlDoc.createTextNode(text));root.appendChild(params);root.appendChild(elem);
this.postXML(xmlDoc)};Wami.App.prototype.playRecording=function(wsessionid,utt_id){var xmlDoc=Wami.utils.xml.newDocument("update");var root=xmlDoc.firstChild;root.setAttribute("type","playrecording");root.setAttribute("wsessionid",wsessionid);root.setAttribute("uttid",utt_id);this.postXML(xmlDoc)};Wami.App.prototype.close=function(wsessionid,utt_id){var xmlDoc=Wami.utils.xml.newDocument("update");var root=xmlDoc.firstChild;root.setAttribute("type","wami_close");this.postXML(xmlDoc)};
Wami.App.prototype.postXML=function(xmlNode,callback){var xmlStr=Wami.utils.xml.toString(xmlNode);this.postXMLString(xmlStr,callback)};
Wami.App.prototype.setTranscript=function(wsessionid,utt_id,transcriber,transcript){var xmldoc=Wami.utils.xml.newDocument("update");var root=xmldoc.firstChild;root.setAttribute("type","transcript");root.setAttribute("wsessionid",wsessionid);root.setAttribute("transcriber",transcriber);root.setAttribute("uttid",utt_id);root.setAttribute("transcription",transcript);var text=xmldoc.createTextNode(transcript);root.appendChild(text);this.postXML(xmldoc)};
Wami.App.prototype.logEvents=function(logs){var xdoc=Wami.utils.xml.newDocument("update");var root=xdoc.firstChild;root.setAttribute("type","logevents");for(var i=0;i<logs.length;i++){var node=xdoc.createElement("event");for(attr in logs[i])node.setAttribute(attr,logs[i][attr]);root.appendChild(node)}this.postXML(xdoc)};Wami.App.prototype.postJSON=function(json){alert("postJSON not yet implemented")};Wami.App.prototype.listen=function(){if(Wami.startListening)Wami.startListening()};
Wami.App.prototype.unlisten=function(){if(Wami.stopListening)Wami.stopListening()};
Wami.App.prototype.record=function(){this.fireAudioEvent(Wami.state.RECORD,Wami.event.STARTING);this.stop();var that=this;var deferred=Wami.utils.createDeferred();var startedfn=Wami.utils.wrapTempFn(function(){that.fireAudioEvent(Wami.state.RECORD,Wami.event.STARTED);deferred.resolveStart()});var donefn=Wami.utils.wrapTempFn(function(){that.fireAudioEvent(Wami.state.RECORD,Wami.event.STOPPED);that.fireAudioEvent(Wami.state.IDLE,Wami.event.ALIVE);deferred.resolve()});var failfn=Wami.utils.wrapTempFn(function(type){that.fireAudioEvent(Wami.state.RECORD,
Wami.event.ERROR);that.fireAudioEvent(Wami.state.IDLE,Wami.event.ALIVE);deferred.rejectWith(type)});Wami.startRecording(this._params.recordUrl,startedfn,donefn,failfn);return deferred};Wami.App.prototype.play=function(arg1,arg2){this.stop();if(typeof arg1=="undefined"){if(this._lastPlayed)return this.play(this._lastPlayed)}else if(typeof arg2=="undefined")return this.playFromURL(this.urls().play(arg1));else return this.playFromURL(this.urls().play(arg1,arg2))};
Wami.App.prototype.playback=function(){if(this._hasRecorded){var deferred=Wami.utils.createDeferred();return deferred.reject()}var url=this.urls().playback();return this.playFromURL(url)};
Wami.App.prototype.playFromURL=function(url){this.fireAudioEvent(Wami.state.PLAY,Wami.event.STARTING);Wami.utils.debug("Playing URL: "+url);this._lastPlayed=url;var that=this;var deferred=Wami.utils.createDeferred();var startedfn=Wami.utils.wrapTempFn(function(){that.fireAudioEvent(Wami.state.PLAY,Wami.event.STARTED);deferred.resolveStart()});var donefn=Wami.utils.wrapTempFn(function(){that.fireAudioEvent(Wami.state.PLAY,Wami.event.STOPPED);that.fireAudioEvent(Wami.state.IDLE,Wami.event.ALIVE);deferred.resolve()});
var failfn=Wami.utils.wrapTempFn(function(arg){that.fireAudioEvent(Wami.state.PLAY,Wami.event.ERROR);that.fireAudioEvent(Wami.state.IDLE,Wami.event.ALIVE);deferred.rejectWith(arg)});Wami.startPlaying(url,startedfn,donefn,failfn);return deferred};
Wami.App.prototype.urls=function(){var that=this;return{playback:function(){return that._params.playUrl+"&operation=playback&rate=11025"},play:function(arg1,arg2){if(typeof arg2=="undefined")return that._params.playUrl+"&operation=proxy&url="+encodeURIComponent(arg1)+"&rate=11025";else return that._params.playUrl+"&operation=playback&rate=11025&fromwsessionid="+encodeURIComponent(arg1)+"&uttid="+arg2},swf:function(){return that._params.contentUrl+"/Wami.swf"},buttons:function(){return that._params.contentUrl+
"/buttons.png"},loading:function(){return that._params.contentUrl+"/loading.gif"}}};Wami.App.prototype.stop=function(){this.stopPlaying();this.stopRecording()};Wami.App.prototype.stopPlaying=function(){if(this.getState()==Wami.state.PLAY)Wami.stopPlaying()};Wami.App.prototype.stopRecording=function(){if(this.getState()==Wami.state.RECORD)Wami.stopRecording()};Wami.App.prototype.getAudioLevel=function(){if(this.getState()==Wami.state.RECORD)return Wami.getRecordingLevel();else return Wami.getPlayingLevel()};
Wami.App.prototype.getState=function(){return this._state};Wami.App.prototype.getLastEvent=function(){return this._lastEvent};var _gWamiAppSingleton;Wami.App.prototype._wamiResponseFormat;Wami.App.prototype._wamiResponseHandlers;Wami.App.prototype._messageElements=null;Wami.App.prototype._wamiEnvironment=null;Wami.App.prototype._wamiShouldPoll=true;
Wami.App.prototype.repoll=function(callback,timeoutBeforeRepoll){var timeout=200;if(timeoutBeforeRepoll)timeout=timeoutBeforeRepoll;var xmlDoc=Wami.utils.xml.newDocument("update");var root=xmlDoc.firstChild;root.setAttribute("type","repoll");root.setAttribute("timeout",timeout);this.postXML(xmlDoc,callback)};Wami.App.prototype.stopPolling=function(callback){Wami.utils.debug("Stop polling");this._wamiShouldPoll=false;this.repoll(callback)};
Wami.App.prototype.startPolling=function(){if(!this._wamiShouldPoll){Wami.utils.debug("Start polling.");this._wamiShouldPoll=true;setTimeout("_gWamiAppSingleton.wamiPoll()",1)}};Wami.App.prototype._messageQueue=new Array;Wami.App.prototype._currentMessage=null;Wami.App.prototype.postXMLString=function(xmlStr,callback){this._messageQueue.push({message:xmlStr,callback:callback});this.trySendingMessage()};
Wami.App.prototype.store=function(storeName,data,callback){var str=Wami.utils.stringifyJSON(data);this._messageQueue.push({message:str,store:storeName,callback:callback});Wami.utils.debug("Message Queue Length: "+this._messageQueue.length);this.trySendingMessage()};
Wami.App.prototype.trySendingMessage=function(){if(this._currentMessage!=null||this._messageQueue.length==0){var reason="Try sending message but message queue length is "+this._messageQueue.length;if(this._currentMessage!=null)reason="current message is still pending. ";Wami.utils.debug("Nothing to send because "+reason);return}this._currentMessage=this._messageQueue.shift();var body=document.getElementsByTagName("body")[0];if(this._messageElements==null){this._messageElements=this.createMessageElements();
body.appendChild(this._messageElements.messageFormDiv);body.appendChild(this._messageElements.messageFrame)}var postID=Wami.utils.uuid();this._messageElements.messageForm.id="wamiForm"+postID;Wami.utils.debug("Sending message ("+postID+") ");Wami.utils.debug(this._currentMessage);var callback=this._currentMessage.callback;Wami.callbacks[postID]=function(){Wami.utils.debug("Message callback: "+postID);if(callback)callback();delete Wami.callbacks[postID]};var params="jsxss=post&postID="+postID;if(this._currentMessage.store){var token=
Wami.utils.getCookie("wamiToken");if(!token){token=postID;Wami.utils.setCookie("wamiToken",token)}params+="&store="+this._currentMessage.store;params+="&token="+token}var posturl=this.appendParamsToURL(this._params.controlUrl,params);this._messageElements.messageForm.setAttribute("accept-charset","UTF-8");this._messageElements.messageForm.setAttribute("action",posturl);this._messageElements.messageField.value=this._currentMessage.message;this._messageElements.messageForm.submit()};
Wami.App.prototype.createMessageElements=function(){var rand=Wami.utils.uuid();var frameName="wamiHiddenFrame"+rand;var divName="wamiFormDiv"+rand;var messageFormDiv=document.createElement("div");messageFormDiv.style.visibility="hidden";messageFormDiv.id=divName;var messageForm=document.createElement("form");var t=(new Date).getTime();messageForm.setAttribute("method","POST");messageForm.setAttribute("target",frameName);var messageField=document.createElement("input");messageField.id="wamiMessage";
messageField.setAttribute("name","wamiMessage");messageField.setAttribute("type","hidden");messageForm.appendChild(messageField);messageFormDiv.appendChild(messageForm);var messageFrame;try{messageFrame=document.createElement('<iframe name="'+frameName+'">')}catch(ex){messageFrame=document.createElement("iframe")}messageFrame.name=frameName;messageFrame.id=frameName;messageFrame.src="about:blank";messageFrame.style.display="none";return{"messageFormDiv":messageFormDiv,"messageField":messageField,
"messageForm":messageForm,"messageFrame":messageFrame}};Wami.App.prototype.appendParamsToURL=function(url,params){if(url.indexOf("?")==-1)return url+"?"+params;else return url+"&"+params};
Wami.App.prototype.wamiPoll=function(){var callback="_gWamiAppSingleton.responseHandler";if(this._wamiEnvironment)callback="parent._gWamiAppSingleton.responseHandler";var hash=Wami.utils.uuid();var params="jsxss=get&polling=true&hash="+hash+"&callback="+callback;var scriptURL=this.appendParamsToURL(this._params.controlUrl,params);Wami.utils.debug("Wami Poll: "+hash);this.appendScript(scriptURL)};
Wami.App.prototype.appendScript=function(scriptURL){if(this._wamiEnvironment==null){var head=document.getElementsByTagName("head")[0];var e=document.createElement("script");e.src=scriptURL;head.appendChild(e)}else{var wamiframe=document.getElementById("wamiScriptLoader");if(wamiframe.isLoaded){if(wamiframe.contentWindow.buildScript)wamiframe.contentWindow.buildScript(scriptURL)}else wamiframe.scriptqueue.push(scriptURL)}};Wami.callbacks=new Array;Wami.scripts=new Array;Wami._callbacks=new Array;
Wami.utils.wrapTempFn=function(fn){return Wami.utils.wrapFn(fn,true)};Wami.utils.wrapFn=function(fn,deleteOnCallback){var hash=Wami.utils.uuid();Wami._callbacks[hash]=function(data){fn(data);if(deleteOnCallback)delete Wami._callbacks[hash]};return"Wami._callbacks['"+hash+"']"};
Wami.App.prototype.retrieve=function(name,callback){var that=this;var fnname=Wami.utils.wrapTempFn(callback);var token=Wami.utils.getCookie("wamiToken");if(!token){Wami.utils.debug("Retrieve failed because no wami token was found.");callback();return}var params="jsxss=get";params+="&retrieve="+name;params+="&token="+token;params+="&callback="+fnname;var scriptURL=this.appendParamsToURL(this._params.controlUrl,params);var e=document.createElement("script");e.src=scriptURL;e.id="retrievalScript";var head=
document.getElementsByTagName("head")[0];head.appendChild(e)};
Wami.App.prototype.setupEnvironment=function(src){var wamiframe=document.createElement("iframe");wamiframe.src=src;wamiframe.id="wamiScriptLoader";wamiframe.isLoaded=false;wamiframe.style.width="1px";wamiframe.style.position="absolute";wamiframe.style.left="-999px";wamiframe.scriptqueue=[];var iframeLoadFunction=function(){var wdw=wamiframe.contentWindow;var q=wamiframe.scriptqueue;var i;var m;for(i=0,m=q.length;i<m;i++)wdw.buildScript(q[i]);wamiframe.isLoaded=true};if(wamiframe.attachEvent)wamiframe.attachEvent("onload",
iframeLoadFunction);else if(wamiframe.addEventListener)wamiframe.addEventListener("load",iframeLoadFunction,true);else wamiframe.onload=iframeLoadFunction;document.body.appendChild(wamiframe)};
Wami.App.prototype.responseHandler=function(xmlStr){if(!this._isReady)return false;Wami.utils.debug("Back from poll with: "+xmlStr);var xmlDoc=Wami.utils.xml.fromString(xmlStr);var replies=xmlDoc.getElementsByTagName("reply");var repollTimeout=10;for(var i=0;i<replies.length;i++){var reply=replies[i];var type=reply.getAttribute("type");if(type=="recresult")this.handleRecResult(reply);else if(type=="play_url")this.play(reply.getAttribute("url"));else if(type=="timeout"){this.handleCallback("onTimeout");
this.fireAudioEvent(Wami.state.IDLE,Wami.event.STOPPING);this.fireAudioEvent(Wami.state.IDLE,Wami.event.STOPPED);return}else if(type=="error"){this.fireAudioEvent(Wami.state.IDLE,Wami.event.ERROR,reply);this.handleCallback("onError",reply.getAttribute("error_type"),reply.getAttribute("message"),reply.getAttribute("details"))}else if(type=="wami_end_turn");else if(type=="stop_polling")this._wamiShouldPoll=false;else if(type=="repoll")repollTimeout=reply.getAttribute("timeout");else if(type=="invalid_key")alert("The developer key for this domain does not match the WAMI database.  This WAMI app will not work properly!");
else if(type=="update_processed"){Wami.utils.debug("Processed... ");Wami.utils.debug(this._currentMessage);this._currentMessage=null;var postID=reply.getAttribute("postID");if(this._messageElements.messageForm.id=="wamiForm"+postID)this._messageElements.messageFrame.src="about:blank";if(!this.isPlayingBack()&&Wami.callbacks[postID])Wami.callbacks[postID]();this.trySendingMessage()}else if(type=="action"){var name=reply.getAttribute("name");var text=this.getTextFromNode(reply);var json=null;if(text)json=
Wami.utils.parseJSON(text);Wami.utils.debug("Replaying action["+name+"] with...");Wami.utils.debug(json);this._actions[name](json)}else this.handleCallback("onMessage",reply)}if(this._wamiShouldPoll)setTimeout(function(){_gWamiAppSingleton.wamiPoll()},repollTimeout)};Wami.App.prototype.getTextFromNode=function(node){if(typeof node.textContent!="undefined")return node.textContent;var text="";for(var x=0;x<node.childNodes.length;x++)text=text+node.childNodes[x].nodeValue;return text};
Wami.App.prototype.appendParam=function(xmlDoc,elem,name,value){if(typeof value!="undefined"&&value!=null){var param=xmlDoc.createElement("param");param.setAttribute("name",name);param.setAttribute("value",typeof value=="boolean"?value?"true":"false":value);elem.appendChild(param)}};
Wami.App.prototype.appendGrammar=function(xmlDoc,elem,grammarOpts){var grammarLanguage=this.getParam(grammarOpts,"language","en-us");var type=this.getParam(grammarOpts,"type","jsgf");var grammar=this.getParam(grammarOpts,"grammar","");if(grammar==""){alert("You must specify a grammar!");return}var node=xmlDoc.createElement("grammar");node.setAttribute("language",grammarLanguage);node.setAttribute("type",type);var text=xmlDoc.createTextNode(grammar);node.appendChild(text);elem.appendChild(node)};
Wami.App.prototype.getParam=function(options,name,defaultValue){var value=typeof options!="undefined"&&options!=null&&typeof options[name]!="undefined"?options[name]:defaultValue;return typeof value=="boolean"?value?"true":"false":value};
Wami.App.prototype.convertXmlRecResultToJson=function(reply){var incremental=reply.getAttribute("incremental")=="true";var utt_id=parseInt(reply.getAttribute("utt_id"));var incremental_index=parseInt(reply.getAttribute("incremental_index"));var hyps=new Array;var xmlHyps=reply.getElementsByTagName("hyp");if(xmlHyps&&xmlHyps.length>0)for(var i=0;i<xmlHyps.length;i++)hyps[i]=this.convertXmlHypToJson(xmlHyps[i]);return{"incremental":incremental,"utt_id":utt_id,"incremental_index":incremental_index,"hyps":hyps}};
Wami.App.prototype.convertXmlHypToJson=function(xmlHyp){var index=parseInt(xmlHyp.getAttribute("index"));var textNode=xmlHyp.getElementsByTagName("text")[0].firstChild;var text=textNode?textNode.data:"";var jsonHyp={"index":index,"text":text};var xmlAggs=xmlHyp.getElementsByTagName("aggregate");if(xmlAggs&&xmlAggs.length>0)jsonHyp["aggregate"]=this.convertXmlAggregateToJson(xmlAggs[0]);return jsonHyp};
Wami.App.prototype.convertXmlAggregateToJson=function(xmlAgg){var index=parseInt(xmlAgg.getAttribute("index"));var partial=xmlAgg.getAttribute("partial")=="true";var kvsHash={};var kvs=xmlAgg.getElementsByTagName("kv");if(kvs)for(var i=0;i<kvs.length;i++)kvsHash[kvs[i].getAttribute("key")]=kvs[i].getAttribute("value");return{"index":index,"partial":partial,"kvs":kvsHash}};
Wami.App.prototype.handleRecResult=function(reply){if(reply.firstChild&&reply.firstChild.nodeType==3){var text=this.getTextFromNode(reply.firstChild);Wami.utils.debug(text);var result=Wami.utils.parseJSON(text);this.handleCallback("onResult",result)}else{var recresult=this.convertXmlRecResultToJson(reply);Wami.utils.debug(recresult);this.handleCallback("onRecognitionResult",recresult);var recobj=this.getRecObject(recresult);this.handleCallback("onRecognition",recobj)}};
Wami.App.prototype.getRecObject=function(result){return{settled:function(){return!result.incremental},uttID:function(){return result.utt_id},count:function(){return result.hyps.length},text:function(index){return this.raw(index)},raw:function(index){if(typeof index=="undefined"){if(this.count()==0)return"";index=0}if(result.hyps&&result.hyps[index])return result.hyps[index].text;return null},get:function(key,index){if(typeof index=="undefined"){if(this.count()==0)return null;index=0}if(result.hyps&&
result.hyps[index]){var aggregate=result.hyps[index].aggregate;if(aggregate&&aggregate.kvs)return aggregate.kvs[key]}return null},partial:function(){if(result.hyps&&result.hyps.length>0&&result.hyps[0].aggregate)return result.hyps[0].aggregate.partial;return false},context:function(c,speaker){var newContext={WAMI_CONTEXT:1,context:c,uttID:result.utt_id};if(typeof(speaker!="undefined"))newContext.speaker=speaker;return newContext}}};Wami.App.prototype.setDefaultContext=function(c){};
Wami.App.prototype.report=function(events){};Wami.App.prototype.handleCallback=function(name,arg1,arg2,arg3,arg4){if(typeof this._wamiResponseHandlers[name]!="undefined")this._wamiResponseHandlers[name](arg1,arg2,arg3,arg4);else Wami.utils.debug("Undefined Handler: "+name)};
Wami.App.prototype.startPlayback=function(playbackID){Wami.utils.debug("Start Playback");var xmldoc=Wami.utils.xml.newDocument("update");var root=xmldoc.firstChild;root.setAttribute("type","playback");root.setAttribute("start_playback",true);root.setAttribute("playback_session",playbackID);this.postXML(xmldoc)};Wami.App.prototype.getSessionID=function(){return this._wsessionid};Wami.App.prototype.isPlayingBack=function(){return typeof this._playbackID!="undefined"};
Wami.App.prototype.registerAction=function(name,callback){this._actions[name]=callback};
Wami.App.prototype.performAction=function(name,data,offset){Wami.utils.debug("Performing action: "+name+" with...");Wami.utils.debug(data);this._actions[name](data);if(!this.isPlayingBack()){var xmldoc=Wami.utils.xml.newDocument("update");var root=xmldoc.firstChild;root.setAttribute("type","action");root.setAttribute("name",name);root.setAttribute("send_back_during_replay","true");if(offset)root.setAttribute("event_time_offset",offset);var json=Wami.utils.stringifyJSON(data);var text=xmldoc.createTextNode(json);
root.appendChild(text);this.postXML(xmldoc)}};Wami.utils.getServletUrl=function(name){return"http://cloud.wami.csail.mit.edu:8080/portal/"+name+";jsessionid=D8D240D232381DD60EEC56320FDF56B0"};Wami=window.Wami||{};
Wami.swfobject=function(){function f(){if(J)return;try{var Z=j.getElementsByTagName("body")[0].appendChild(C("span"));Z.parentNode.removeChild(Z)}catch(aa){return}J=true;var X=U.length;for(var Y=0;Y<X;Y++)U[Y]()}function K(X){if(J)X();else U[U.length]=X}function s(Y){if(typeof O.addEventListener!=D)O.addEventListener("load",Y,false);else if(typeof j.addEventListener!=D)j.addEventListener("load",Y,false);else if(typeof O.attachEvent!=D)i(O,"onload",Y);else if(typeof O.onload=="function"){var X=O.onload;
O.onload=function(){X();Y()}}else O.onload=Y}function h(){if(T)V();else H()}function V(){var X=j.getElementsByTagName("body")[0];var aa=C(r);aa.setAttribute("type",q);var Z=X.appendChild(aa);if(Z){var Y=0;(function(){if(typeof Z.GetVariable!=D){var ab=Z.GetVariable("$version");if(ab){ab=ab.split(" ")[1].split(",");M.pv=[parseInt(ab[0],10),parseInt(ab[1],10),parseInt(ab[2],10)]}}else if(Y<10){Y++;setTimeout(arguments.callee,10);return}X.removeChild(aa);Z=null;H()})()}else H()}function H(){var ag=o.length;
if(ag>0)for(var af=0;af<ag;af++){var Y=o[af].id;var ab=o[af].callbackFn;var aa={success:false,id:Y};if(M.pv[0]>0){var ae=c(Y);if(ae)if(F(o[af].swfVersion)&&!(M.wk&&M.wk<312)){w(Y,true);if(ab){aa.success=true;aa.ref=z(Y);ab(aa)}}else if(o[af].expressInstall&&A()){var ai={};ai.data=o[af].expressInstall;ai.width=ae.getAttribute("width")||"0";ai.height=ae.getAttribute("height")||"0";if(ae.getAttribute("class"))ai.styleclass=ae.getAttribute("class");if(ae.getAttribute("align"))ai.align=ae.getAttribute("align");
var ah={};var X=ae.getElementsByTagName("param");var ac=X.length;for(var ad=0;ad<ac;ad++)if(X[ad].getAttribute("name").toLowerCase()!="movie")ah[X[ad].getAttribute("name")]=X[ad].getAttribute("value");P(ai,ah,Y,ab)}else{p(ae);if(ab)ab(aa)}}else{w(Y,true);if(ab){var Z=z(Y);if(Z&&typeof Z.SetVariable!=D){aa.success=true;aa.ref=Z}ab(aa)}}}}function z(aa){var X=null;var Y=c(aa);if(Y&&Y.nodeName=="OBJECT")if(typeof Y.SetVariable!=D)X=Y;else{var Z=Y.getElementsByTagName(r)[0];if(Z)X=Z}return X}function A(){return!a&&
F("6.0.65")&&(M.win||M.mac)&&!(M.wk&&M.wk<312)}function P(aa,ab,X,Z){a=true;E=Z||null;B={success:false,id:X};var ae=c(X);if(ae){if(ae.nodeName=="OBJECT"){l=g(ae);Q=null}else{l=ae;Q=X}aa.id=R;if(typeof aa.width==D||!/%$/.test(aa.width)&&parseInt(aa.width,10)<310)aa.width="310";if(typeof aa.height==D||!/%$/.test(aa.height)&&parseInt(aa.height,10)<137)aa.height="137";j.title=j.title.slice(0,47)+" - Flash Player Installation";var ad=M.ie&&M.win?"ActiveX":"PlugIn";var ac="MMredirectURL="+O.location.toString().replace(/&/g,
"%26")+"&MMplayerType="+ad+"&MMdoctitle="+j.title;if(typeof ab.flashvars!=D)ab.flashvars+="&"+ac;else ab.flashvars=ac;if(M.ie&&M.win&&ae.readyState!=4){var Y=C("div");X+="SWFObjectNew";Y.setAttribute("id",X);ae.parentNode.insertBefore(Y,ae);ae.style.display="none";(function(){if(ae.readyState==4)ae.parentNode.removeChild(ae);else setTimeout(arguments.callee,10)})()}u(aa,ab,X)}}function p(Y){if(M.ie&&M.win&&Y.readyState!=4){var X=C("div");Y.parentNode.insertBefore(X,Y);X.parentNode.replaceChild(g(Y),
X);Y.style.display="none";(function(){if(Y.readyState==4)Y.parentNode.removeChild(Y);else setTimeout(arguments.callee,10)})()}else Y.parentNode.replaceChild(g(Y),Y)}function g(ab){var aa=C("div");if(M.win&&M.ie)aa.innerHTML=ab.innerHTML;else{var Y=ab.getElementsByTagName(r)[0];if(Y){var ad=Y.childNodes;if(ad){var X=ad.length;for(var Z=0;Z<X;Z++)if(!(ad[Z].nodeType==1&&ad[Z].nodeName=="PARAM")&&!(ad[Z].nodeType==8))aa.appendChild(ad[Z].cloneNode(true))}}}return aa}function u(ai,ag,Y){var X;var aa=
c(Y);if(M.wk&&M.wk<312)return X;if(aa){if(typeof ai.id==D)ai.id=Y;if(M.ie&&M.win){var ah="";for(var ae in ai)if(ai[ae]!=Object.prototype[ae])if(ae.toLowerCase()=="data")ag.movie=ai[ae];else if(ae.toLowerCase()=="styleclass")ah+=' class="'+ai[ae]+'"';else if(ae.toLowerCase()!="classid")ah+=" "+ae+'="'+ai[ae]+'"';var af="";for(var ad in ag)if(ag[ad]!=Object.prototype[ad])af+='<param name="'+ad+'" value="'+ag[ad]+'" />';aa.outerHTML='<object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000"'+ah+">"+
af+"</object>";N[N.length]=ai.id;X=c(ai.id)}else{var Z=C(r);Z.setAttribute("type",q);for(var ac in ai)if(ai[ac]!=Object.prototype[ac])if(ac.toLowerCase()=="styleclass")Z.setAttribute("class",ai[ac]);else if(ac.toLowerCase()!="classid")Z.setAttribute(ac,ai[ac]);for(var ab in ag)if(ag[ab]!=Object.prototype[ab]&&ab.toLowerCase()!="movie")e(Z,ab,ag[ab]);aa.parentNode.replaceChild(Z,aa);X=Z}}return X}function e(Z,X,Y){var aa=C("param");aa.setAttribute("name",X);aa.setAttribute("value",Y);Z.appendChild(aa)}
function y(Y){var X=c(Y);if(X&&X.nodeName=="OBJECT")if(M.ie&&M.win){X.style.display="none";(function(){if(X.readyState==4)b(Y);else setTimeout(arguments.callee,10)})()}else X.parentNode.removeChild(X)}function b(Z){var Y=c(Z);if(Y){for(var X in Y)if(typeof Y[X]=="function")Y[X]=null;Y.parentNode.removeChild(Y)}}function c(Z){var X=null;try{X=j.getElementById(Z)}catch(Y){}return X}function C(X){return j.createElement(X)}function i(Z,X,Y){Z.attachEvent(X,Y);I[I.length]=[Z,X,Y]}function F(Z){var Y=M.pv;
var X=Z.split(".");X[0]=parseInt(X[0],10);X[1]=parseInt(X[1],10)||0;X[2]=parseInt(X[2],10)||0;return Y[0]>X[0]||Y[0]==X[0]&&Y[1]>X[1]||Y[0]==X[0]&&Y[1]==X[1]&&Y[2]>=X[2]?true:false}function v(ac,Y,ad,ab){if(M.ie&&M.mac)return;var aa=j.getElementsByTagName("head")[0];if(!aa)return;var X=ad&&typeof ad=="string"?ad:"screen";if(ab){n=null;G=null}if(!n||G!=X){var Z=C("style");Z.setAttribute("type","text/css");Z.setAttribute("media",X);n=aa.appendChild(Z);if(M.ie&&M.win&&typeof j.styleSheets!=D&&j.styleSheets.length>
0)n=j.styleSheets[j.styleSheets.length-1];G=X}if(M.ie&&M.win){if(n&&typeof n.addRule==r)n.addRule(ac,Y)}else if(n&&typeof j.createTextNode!=D)n.appendChild(j.createTextNode(ac+" {"+Y+"}"))}function w(Z,X){if(!m)return;var Y=X?"visible":"hidden";if(J&&c(Z))c(Z).style.visibility=Y;else v("#"+Z,"visibility:"+Y)}function L(Y){var Z=/[\\\"<>\.;]/;var X=Z.exec(Y)!=null;return X&&typeof encodeURIComponent!=D?encodeURIComponent(Y):Y}var D="undefined";var r="object";var S="Shockwave Flash";var W="ShockwaveFlash.ShockwaveFlash";
var q="application/x-shockwave-flash";var R="SWFObjectExprInst";var x="onreadystatechange";var O=window;var j=document;var t=navigator;var T=false;var U=[h];var o=[];var N=[];var I=[];var l;var Q;var E;var B;var J=false;var a=false;var n;var G;var m=true;var M=function(){var aa=typeof j.getElementById!=D&&typeof j.getElementsByTagName!=D&&typeof j.createElement!=D;var ah=t.userAgent.toLowerCase();var Y=t.platform.toLowerCase();var ae=Y?/win/.test(Y):/win/.test(ah);var ac=Y?/mac/.test(Y):/mac/.test(ah);
var af=/webkit/.test(ah)?parseFloat(ah.replace(/^.*webkit\/(\d+(\.\d+)?).*$/,"$1")):false;var X=!+"\u000b1";var ag=[0,0,0];var ab=null;if(typeof t.plugins!=D&&typeof t.plugins[S]==r){ab=t.plugins[S].description;if(ab&&!(typeof t.mimeTypes!=D&&t.mimeTypes[q]&&!t.mimeTypes[q].enabledPlugin)){T=true;X=false;ab=ab.replace(/^.*\s+(\S+\s+\S+$)/,"$1");ag[0]=parseInt(ab.replace(/^(.*)\..*$/,"$1"),10);ag[1]=parseInt(ab.replace(/^.*\.(.*)\s.*$/,"$1"),10);ag[2]=/[a-zA-Z]/.test(ab)?parseInt(ab.replace(/^.*[a-zA-Z]+(.*)$/,
"$1"),10):0}}else if(typeof O.ActiveXObject!=D)try{var ad=new ActiveXObject(W);if(ad){ab=ad.GetVariable("$version");if(ab){X=true;ab=ab.split(" ")[1].split(",");ag=[parseInt(ab[0],10),parseInt(ab[1],10),parseInt(ab[2],10)]}}}catch(Z){}return{w3:aa,pv:ag,wk:af,ie:X,win:ae,mac:ac}}();var k=function(){if(!M.w3)return;if(typeof j.readyState!=D&&j.readyState=="complete"||typeof j.readyState==D&&(j.getElementsByTagName("body")[0]||j.body))f();if(!J){if(typeof j.addEventListener!=D)j.addEventListener("DOMContentLoaded",
f,false);if(M.ie&&M.win){j.attachEvent(x,function(){if(j.readyState=="complete"){j.detachEvent(x,arguments.callee);f()}});if(O==top)(function(){if(J)return;try{j.documentElement.doScroll("left")}catch(X){setTimeout(arguments.callee,0);return}f()})()}if(M.wk)(function(){if(J)return;if(!/loaded|complete/.test(j.readyState)){setTimeout(arguments.callee,0);return}f()})();s(f)}}();var d=function(){if(M.ie&&M.win)window.attachEvent("onunload",function(){var ac=I.length;for(var ab=0;ab<ac;ab++)I[ab][0].detachEvent(I[ab][1],
I[ab][2]);var Z=N.length;for(var aa=0;aa<Z;aa++)y(N[aa]);for(var Y in M)M[Y]=null;M=null;for(var X in swfobject)swfobject[X]=null;swfobject=null})}();return{registerObject:function(ab,X,aa,Z){if(M.w3&&ab&&X){var Y={};Y.id=ab;Y.swfVersion=X;Y.expressInstall=aa;Y.callbackFn=Z;o[o.length]=Y;w(ab,false)}else if(Z)Z({success:false,id:ab})},getObjectById:function(X){if(M.w3)return z(X)},embedSWF:function(ab,ah,ae,ag,Y,aa,Z,ad,af,ac){var X={success:false,id:ah};if(M.w3&&!(M.wk&&M.wk<312)&&ab&&ah&&ae&&ag&&
Y){w(ah,false);K(function(){ae+="";ag+="";var aj={};if(af&&typeof af===r)for(var al in af)aj[al]=af[al];aj.data=ab;aj.width=ae;aj.height=ag;var am={};if(ad&&typeof ad===r)for(var ak in ad)am[ak]=ad[ak];if(Z&&typeof Z===r)for(var ai in Z)if(typeof am.flashvars!=D)am.flashvars+="&"+ai+"="+Z[ai];else am.flashvars=ai+"="+Z[ai];if(F(Y)){var an=u(aj,am,ah);if(aj.id==ah)w(ah,true);X.success=true;X.ref=an}else if(aa&&A()){aj.data=aa;P(aj,am,ah,ac);return}else w(ah,true);if(ac)ac(X)})}else if(ac)ac(X)},switchOffAutoHideShow:function(){m=
false},ua:M,getFlashPlayerVersion:function(){return{major:M.pv[0],minor:M.pv[1],release:M.pv[2]}},hasFlashPlayerVersion:F,createSWF:function(Z,Y,X){if(M.w3)return u(Z,Y,X);else return undefined},showExpressInstall:function(Z,aa,X,Y){if(M.w3&&A())P(Z,aa,X,Y)},removeSWF:function(X){if(M.w3)y(X)},createCSS:function(aa,Z,Y,X){if(M.w3)v(aa,Z,Y,X)},addDomLoadEvent:K,addLoadEvent:s,getQueryParamValue:function(aa){var Z=j.location.search||j.location.hash;if(Z){if(/\?/.test(Z))Z=Z.split("?")[1];if(aa==null)return L(Z);
var Y=Z.split("&");for(var X=0;X<Y.length;X++)if(Y[X].substring(0,Y[X].indexOf("="))==aa)return L(Y[X].substring(Y[X].indexOf("=")+1))}return""},expressInstallCallback:function(){if(a){var X=c(R);if(X&&l){X.parentNode.replaceChild(l,X);if(Q){w(Q,true);if(M.ie&&M.win)l.style.display="block"}if(E)E(B)}a=false}}}}();if(!this.JSON)this.JSON={};
(function(){function f(n){return n<10?"0"+n:n}function quote(string){escapable.lastIndex=0;return escapable.test(string)?'"'+string.replace(escapable,function(a){var c=meta[a];return typeof c==="string"?c:"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)})+'"':'"'+string+'"'}function str(key,holder){var i;var k;var v;var length;var mind=gap;var partial;var value=holder[key];if(value&&typeof value==="object"&&typeof value.toJSON==="function")value=value.toJSON(key);if(typeof rep==="function")value=
rep.call(holder,key,value);switch(typeof value){case "string":return quote(value);case "number":return isFinite(value)?String(value):"null";case "boolean":case "null":return String(value);case "object":if(!value)return"null";gap+=indent;partial=[];if(Object.prototype.toString.apply(value)==="[object Array]"){length=value.length;for(i=0;i<length;i+=1)partial[i]=str(i,value)||"null";v=partial.length===0?"[]":gap?"[\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"]":"["+partial.join(",")+"]";gap=mind;return v}if(rep&&
typeof rep==="object"){length=rep.length;for(i=0;i<length;i+=1){k=rep[i];if(typeof k==="string"){v=str(k,value);if(v)partial.push(quote(k)+(gap?": ":":")+v)}}}else for(k in value)if(Object.hasOwnProperty.call(value,k)){v=str(k,value);if(v)partial.push(quote(k)+(gap?": ":":")+v)}v=partial.length===0?"{}":gap?"{\n"+gap+partial.join(",\n"+gap)+"\n"+mind+"}":"{"+partial.join(",")+"}";gap=mind;return v}}if(typeof Date.prototype.toJSON!=="function"){Date.prototype.toJSON=function(key){return isFinite(this.valueOf())?
this.getUTCFullYear()+"-"+f(this.getUTCMonth()+1)+"-"+f(this.getUTCDate())+"T"+f(this.getUTCHours())+":"+f(this.getUTCMinutes())+":"+f(this.getUTCSeconds())+"Z":null};String.prototype.toJSON=Number.prototype.toJSON=Boolean.prototype.toJSON=function(key){return this.valueOf()}}var cx=/[\u0000\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;var escapable=/[\\\"\x00-\x1f\x7f-\x9f\u00ad\u0600-\u0604\u070f\u17b4\u17b5\u200c-\u200f\u2028-\u202f\u2060-\u206f\ufeff\ufff0-\uffff]/g;
var gap;var indent;var meta={"\u0008":"\\b","\t":"\\t","\n":"\\n","\u000c":"\\f","\r":"\\r",'"':'\\"',"\\":"\\\\"};var rep;if(typeof JSON.stringify!=="function")JSON.stringify=function(value,replacer,space){var i;gap="";indent="";if(typeof space==="number")for(i=0;i<space;i+=1)indent+=" ";else if(typeof space==="string")indent=space;rep=replacer;if(replacer&&typeof replacer!=="function"&&(typeof replacer!=="object"||typeof replacer.length!=="number"))throw new Error("JSON.stringify");return str("",
{"":value})};if(typeof JSON.parse!=="function")JSON.parse=function(text,reviver){function walk(holder,key){var k;var v;var value=holder[key];if(value&&typeof value==="object")for(k in value)if(Object.hasOwnProperty.call(value,k)){v=walk(value,k);if(v!==undefined)value[k]=v;else delete value[k]}return reviver.call(holder,key,value)}var j;cx.lastIndex=0;if(cx.test(text))text=text.replace(cx,function(a){return"\\u"+("0000"+a.charCodeAt(0).toString(16)).slice(-4)});if(/^[\],:{}\s]*$/.test(text.replace(/\\(?:["\\\/bfnrt]|u[0-9a-fA-F]{4})/g,
"@").replace(/"[^"\\\n\r]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?/g,"]").replace(/(?:^|:|,)(?:\s*\[)+/g,""))){j=eval("("+text+")");return typeof reviver==="function"?walk({"":j},""):j}throw new SyntaxError("JSON.parse");}})();